fix error caused by supplied arguments
loadManifest() handles multiple object parameters instead of array of object

fixed TypeError: undefined is not a function